### ISSUE TITLE
`parse_options': invalid option: --0 (OptionParser::InvalidOption)

### ISSUE THREAD

**Issue by Oshuma** [dpashkevich/grunt-jsduck#7]
When running the grunt task, jsduck seems to be getting passed '--0' (zero) as an argument.  The docs are generated fine, but are placed in a directory named '`undefined`' instead of the `dest` directory.  Running the `jsduck` binary on its own, with the same options set in the gruntfile, works just fine.

Versions:
grunt v0.4.2
grunt-cli v0.1.11
jsduck v5.3.4
grunt-jsduck v1.0.0

Gruntfile config:

``` javascript
jsduck: {
  src: ['Resources/'],
  dest: 'docs',
  options: {
    'tests': true,
    'title': 'Project Docs'
  }
},
```

Stacktrace:

``` text
/path/to/gems/jsduck-5.3.4/lib/jsduck/options.rb:871:in `parse_options': invalid option: --0 (OptionParser::InvalidOption)
    from /path/to/gems/jsduck-5.3.4/lib/jsduck/options.rb:171:in `parse!'
    from /path/to/gems/jsduck-5.3.4/bin/jsduck:24:in `<top (required)>'
    from /path/to/bin/jsduck:23:in `load'
    from /path/to/bin/jsduck:23:in `<main>'
Warning: /path/to/gems/jsduck-5.3.4/lib/jsduck/options.rb:871:in `parse_options': invalid option: --0 (OptionParser::InvalidOption)
    from /path/to/gems/jsduck-5.3.4/lib/jsduck/options.rb:171:in `parse!'
    from /path/to/gems/jsduck-5.3.4/bin/jsduck:24:in `<top (required)>'
    from /path/to/bin/jsduck:23:in `load'
    from /path/to/bin/jsduck:23:in `<main>' Use --force to continue.

Aborted due to warnings.
```

**Comment by dpashkevich** [comment]
Thanks for reporting!

`grunt-jsduck`, like many other grunt tasks, is a [multitask](http://gruntjs.com/creating-tasks#multi-tasks) this means that your task configuration has to start with a _target_ objec that, in turn, contains the options that you have already specified:

``` javascript
    jsduck: {
      dist: {   // <-- this is a target (the name is arbitrary)
        src: ['Resources/'],
        dest: 'docs',
        options: {
          'tests': true,
          'title': 'Project Docs'
        }
      }
    }, 
```

Targets allow you to run the same task multiple times with different configuration, but I agree that it's reduntant when you have just one target and can confuse new users. I'm closing this ticket but I'll think of more ways to specify task's configuration.

**Comment by Oshuma** [comment]
Ah, cool.  Thanks for clarifying.
