### ISSUE TITLE
grunt-lib-contrib is deprecated

### ISSUE THREAD

**Issue by sindresorhus** [dpashkevich/grunt-jsduck#8]
I noticed you have [grunt-lib-contrib](https://github.com/gruntjs/grunt-lib-contrib) as a dependency.

It's deprecated and I would recommend you switch to the extracted modules instead:
`stripPath` => [strip-path](https://github.com/sindresorhus/strip-path)
`minMaxInfo` => [maxmin](https://github.com/sindresorhus/maxmin)
`getNamespaceDeclaration` => [ticket](https://github.com/gruntjs/grunt-lib-contrib/issues/9)

**Comment by dpashkevich** [comment]
Thanks for notifying, I updated my package!

I was actually using a pretty old version of it, `0.4.x`, and used `optToArgs` which later made it into your module `dargs`. You should add that to the changelog

`optsToArgs` => [dargs](https://github.com/sindresorhus/dargs)
